// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	models "github.com/Pklerik/gophKeep/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockUserRepositoryInterface is a mock of UserRepositoryInterface interface.
type MockUserRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryInterfaceMockRecorder
}

// MockUserRepositoryInterfaceMockRecorder is the mock recorder for MockUserRepositoryInterface.
type MockUserRepositoryInterfaceMockRecorder struct {
	mock *MockUserRepositoryInterface
}

// NewMockUserRepositoryInterface creates a new mock instance.
func NewMockUserRepositoryInterface(ctrl *gomock.Controller) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepositoryInterface) CreateUser(id, username, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", id, username, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositoryInterfaceMockRecorder) CreateUser(id, username, passwordHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepositoryInterface)(nil).CreateUser), id, username, passwordHash)
}

// GetUserByID mocks base method.
func (m *MockUserRepositoryInterface) GetUserByID(id string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetUserByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetUserByID), id)
}

// GetUserByUsername mocks base method.
func (m *MockUserRepositoryInterface) GetUserByUsername(username string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", username)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockUserRepositoryInterfaceMockRecorder) GetUserByUsername(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockUserRepositoryInterface)(nil).GetUserByUsername), username)
}

// MockSecretRepositoryInterface is a mock of SecretRepositoryInterface interface.
type MockSecretRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSecretRepositoryInterfaceMockRecorder
}

// MockSecretRepositoryInterfaceMockRecorder is the mock recorder for MockSecretRepositoryInterface.
type MockSecretRepositoryInterfaceMockRecorder struct {
	mock *MockSecretRepositoryInterface
}

// NewMockSecretRepositoryInterface creates a new mock instance.
func NewMockSecretRepositoryInterface(ctrl *gomock.Controller) *MockSecretRepositoryInterface {
	mock := &MockSecretRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockSecretRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretRepositoryInterface) EXPECT() *MockSecretRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CreateSecret mocks base method.
func (m *MockSecretRepositoryInterface) CreateSecret(secret *models.Secret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSecret", secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSecret indicates an expected call of CreateSecret.
func (mr *MockSecretRepositoryInterfaceMockRecorder) CreateSecret(secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSecret", reflect.TypeOf((*MockSecretRepositoryInterface)(nil).CreateSecret), secret)
}

// DeleteSecret mocks base method.
func (m *MockSecretRepositoryInterface) DeleteSecret(id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSecret", id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSecret indicates an expected call of DeleteSecret.
func (mr *MockSecretRepositoryInterfaceMockRecorder) DeleteSecret(id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSecret", reflect.TypeOf((*MockSecretRepositoryInterface)(nil).DeleteSecret), id, userID)
}

// GetSecretByID mocks base method.
func (m *MockSecretRepositoryInterface) GetSecretByID(id string) (*models.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretByID", id)
	ret0, _ := ret[0].(*models.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretByID indicates an expected call of GetSecretByID.
func (mr *MockSecretRepositoryInterfaceMockRecorder) GetSecretByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretByID", reflect.TypeOf((*MockSecretRepositoryInterface)(nil).GetSecretByID), id)
}

// GetSecretsSince mocks base method.
func (m *MockSecretRepositoryInterface) GetSecretsSince(userID string, since time.Time) ([]models.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretsSince", userID, since)
	ret0, _ := ret[0].([]models.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSecretsSince indicates an expected call of GetSecretsSince.
func (mr *MockSecretRepositoryInterfaceMockRecorder) GetSecretsSince(userID, since interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretsSince", reflect.TypeOf((*MockSecretRepositoryInterface)(nil).GetSecretsSince), userID, since)
}

// GetUserSecrets mocks base method.
func (m *MockSecretRepositoryInterface) GetUserSecrets(userID string) ([]models.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSecrets", userID)
	ret0, _ := ret[0].([]models.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSecrets indicates an expected call of GetUserSecrets.
func (mr *MockSecretRepositoryInterfaceMockRecorder) GetUserSecrets(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSecrets", reflect.TypeOf((*MockSecretRepositoryInterface)(nil).GetUserSecrets), userID)
}

// UpdateSecret mocks base method.
func (m *MockSecretRepositoryInterface) UpdateSecret(secret *models.Secret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSecret", secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSecret indicates an expected call of UpdateSecret.
func (mr *MockSecretRepositoryInterfaceMockRecorder) UpdateSecret(secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSecret", reflect.TypeOf((*MockSecretRepositoryInterface)(nil).UpdateSecret), secret)
}
